services:
  db:
    image: mysql:8.2.0
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
    command: --default-authentication-plugin=mysql_native_password
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
      MYSQL_HOST_NAME: db
    depends_on:
      - db
    tty: true
    stdin_open: true

  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./backend/api/tmp/sockets:/app/tmp/sockets
      - ./frontend/app/dist:/app/public
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80
    depends_on:
      - backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - backend
    tty: true
    stdin_open: true